[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

fuzz-runs = 100
optimizer = true          # Enable or disable the solc optimizer
optimizer_runs = 200      # The number of optimizer runs
verbosity = 3             # The verbosity of tests

[profile.pull_request]
fuzz_runs = 1000

[profile.push_to_main]
fuzz_runs = 50000
fuzz_max_global_rejects = 262144
fuzz_max_local_rejects = 4096